#!/usr/bin/python

print "Content-Type: text/html\n\n"

print '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">'
print '<HTML>'
print '<HEAD>'
print '	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">'
print '	<TITLE></TITLE>'
print '	<META NAME="GENERATOR" CONTENT="OpenOffice.org 3.2  (Unix)">'
print '	<META NAME="AUTHOR" CONTENT="James Valleroy">'
print '	<META NAME="CREATED" CONTENT="20100906;15552300">'
print '	<META NAME="CHANGEDBY" CONTENT="James Valleroy">'
print '	<META NAME="CHANGED" CONTENT="20100906;18310400">'
print '	<STYLE TYPE="text/css">'
print '	<!--'
print '		H4.cjk { font-family: "WenQuanYi Zen Hei" }'
print '		H4.ctl { font-family: "Lohit Devanagari" }'
print '	-->'
print '	</STYLE>'
print '</HEAD>'
print '<BODY LANG="en-US" DIR="LTR">'
print '<H1><A HREF="index-render.py"><U>Free Speech Board</U></A></H1>'
print '<H4 CLASS="western"><I>You are on Node #1 of N.</I></H4>'
print '<P STYLE="font-style: normal">Free Speech Board is a simple demo'
print 'application for a wireless mesh network.</P>'
print '<P STYLE="font-style: normal">You can help to extend the range of'
print 'this mesh network.  You can turn your laptop into an FSB node:</P>'
print '<OL>'
print '	<LI><P STYLE="font-style: normal">Install OLSR.</P>'
print '	<LI><P STYLE="font-style: normal">Install Apache web server.</P>'
print '	<LI><P STYLE="font-style: normal">Install CouchDB.</P>'
print '	<LI><P STYLE="font-style: normal">Install Python.</P>'
print '	<LI><P STYLE="font-style: normal">Copy our stuff to web root.</P>'
print '</OL>'
print '</BODY>'
print '</HTML>'

